### ISSUE TITLE
write features aren't working. unable to get reboot switch

### ISSUE THREAD

**Issue by rajkhan0714** [kvj/hass_openwrt#14]
I did everything as per your instructions and I am glad it works.
But the only reason I wanted to use this because I want a restart switch to reboot my openwrt router at a specific time.
and the problem is that it doesn't show any switch only shows 4 sensors
![Screenshot 2023-03-27 at 11 55 19 PM](https://user-images.githubusercontent.com/44030340/228032948-b1cf85ec-51ba-4c4a-82b8-4f5e64d8fdca.png)
![Screenshot 2023-03-28 at 12 00 58 AM](https://user-images.githubusercontent.com/44030340/228034156-2b13ee08-8a3e-4993-a29e-f080156d018d.png)
![Screenshot 2023-03-28 at 12 01 25 AM](https://user-images.githubusercontent.com/44030340/228034175-e6ecbcac-d55c-4d79-8f0c-48f990a26dd4.png)

**Comment by kvj** [comment]
Please run the following commands from the router command line (via ssh) and check whether ubus interfaces available or not:

```
ubus list
```

```
ubus -v list system
```

**Comment by rajkhan0714** [comment]
tried adding "file": "/sbin/reboot": [ "exec" ] but that didn't help either.
![Screenshot 2023-03-28 at 2 50 30 PM](https://user-images.githubusercontent.com/44030340/228191174-9ca7e062-834c-4473-aeeb-5beb5422c8fd.png)

**Comment by kvj** [comment]
wait, there's no such sensor and/or button for the reboot. Please try to call service `openwrt.reboot`

**Comment by rajkhan0714** [comment]
It works, thanks a lot.
I didn't know I could use call service and that there's an option openwrt.reboot is availble.
Thanks A lot.
![Capture](https://user-images.githubusercontent.com/44030340/228215784-df5bbcf4-cbfa-4226-8b0e-03dd9f80edb1.PNG)
