### ISSUE TITLE
 Setup failed for custom integration openwrt: Unable to import component: cannot import name 'SupportsResponse' from 'homeassistant.core' 

### ISSUE THREAD

**Issue by michelep** [kvj/hass_openwrt#25]
Hi all,

latest HomeAssistant docker release 2023.1.7 and 0.1.0 of openwrt. On restart, i got this error:

` Setup failed for custom integration openwrt: Unable to import component: cannot import name 'SupportsResponse' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py) `

Any hint?

**Comment by kvj** [comment]
It's definitely a time for upgrade. Your home assistant version is not supported

**Comment by michelep** [comment]
> It's definitely a time for upgrade. Your home assistant version is not supported

Thanks. However I have the latest "docker" version. Any hint how to upgrade on docker with latest release? Seems that's not so easy...

**Comment by kvj** [comment]
Nothing has changed. They keep pushing docker images https://hub.docker.com/r/homeassistant/home-assistant/tags

Platform installation https://www.home-assistant.io/installation/linux#platform-installation is still officially supported

**Comment by michelep** [comment]
Done. Thanks!
